### PR TITLE
replace cygwin with msys2 [skip travis]

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by uilianries** [comment]
I'm curious if this change could break any user. Are both cygwin and mingw compatible?

**Comment by SSE4** [comment]
I think both could be used for build, but what is the motivation?

**Comment by ericLemanissier** [comment]
In theory the environment used to do the compilation (cygwin vs msys2) should have no impact. MSYS2 is just a more usual setting when you want do "native" compilation, and don't want to depend on the cygwin runtime. Most of bincrafters recipe are already on msys2 (https://github.com/search?q=org%3Abincrafters+msys2_installer&type=Code vs https://github.com/search?q=org%3Abincrafters+cygwin_installer&type=Code)

**Comment by uilianries** [comment]
Okay, sounds plausible.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
